server:
  port: 80
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

#mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.38.101.172:3306/wifiscan?useUnicode=true&characterEncoding=UTF-8&servserTimezone=Asia/Shanghai
    #url: jdbc:mysql://sh-cynosdbmysql-grp-0c6uxq0q.sql.tencentcdb.com:25361/wifiscan?useUnicode=true&characterEncoding=UTF-8&servserTimezone=Asia/Shanghai
    username: wifiscan
    password: xyd123456@

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
